trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Bhoomika Azure Terraform!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publicKey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=${client_id} -var client_secret=${client_secret} -var ssh_public_key=${publicKey.secureFilePath}'
    backendType: 'azurerm'
    backendServiceArm: 'azure_poc'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageaccbhoomi'
    backendAzureRmContainerName: 'storageaccbhoomicontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'